const insectEntries = [
  {
    day: 1,
    title: "Jack Jumper Ant",
    category: "Hymenoptera",
    species: "Myrmecia piliventris — commonly known as the Jack Jumper Ant, a member of the bull ant family native to Australia.",
    meet: "The Jack Jumper Ant is small, aggressive and entirely unbothered by the fact that it can kill you. It moves in unpredictable leaping bounds rather than the orderly marching lines you expect from ants, which makes it look slightly unhinged. It will also turn to face you from a distance, which means it knows you are there and has decided to make that your problem.",
    where: "Found almost exclusively in southeastern Australia and Tasmania, in woodland and bushland areas with rocky, sandy soil. Tasmanians are disproportionately familiar with it in a way they would rather not be.",
    superpower: "Unlike most ants which bite and spray acid, the Jack Jumper stings repeatedly and injects venom directly into its target. It can see you coming from a remarkable distance for an insect its size and will orient its body to face you. It is not retreating.",
    fun_fact: "The Jack Jumper Ant is responsible for more deaths in Tasmania than spiders, snakes and sharks combined. A specific desensitisation vaccine had to be developed exclusively for this one ant because standard treatments were not enough.",
  },
  {
    day: 2,
    title: "Mantis Shrimp",
    category: "Stomatopoda",
    species: "Odontodactylus scyllarus — the Peacock Mantis Shrimp, despite its name not a shrimp at all but a stomatopod crustacean found in tropical waters.",
    meet: "The Mantis Shrimp looks like someone gave a rainbow a bad attitude. It is one of the most visually striking creatures in the ocean, wearing colours so vivid they seem digitally enhanced. It is also one of the most violent things in any body of water it inhabits, which makes the beauty deeply misleading.",
    where: "Tropical and subtropical waters of the Indian and Pacific Oceans, typically living in burrows on the seafloor in coral reef environments. It is territorial, solitary and will attack anything that enters its space including human fingers.",
    superpower: "Its club-like appendages can strike at the speed of a bullet, accelerating at over 10,000 g and reaching speeds of 23 metres per second. The strike is so fast it creates a cavitation bubble that produces a shockwave powerful enough to stun or kill prey even if the physical blow misses. It can punch through aquarium glass.",
    fun_fact: "The Mantis Shrimp has 16 types of photoreceptor cells in its eyes. Humans have 3. Despite this it is believed to process colour less sophisticatedly than humans, meaning it sees more colours but may understand them less. Scientists are still genuinely arguing about what it actually experiences.",
  },
  {
    day: 3,
    title: "Bombardier Beetle",
    category: "Coleoptera",
    species: "Brachinus species — the Bombardier Beetle, a ground beetle found across every continent except Antarctica.",
    meet: "The Bombardier Beetle is a small, unremarkable looking insect that has developed what can only be described as a chemical weapon stored inside its own body. It looks like it should be harmless. It is not. It has been running this particular defence strategy for millions of years and shows no signs of stopping.",
    where: "Found across most of the world in soil, woodland, grassland and under stones near water. Common in Europe, Asia, Africa and the Americas. Easy to overlook because of its modest appearance, which is rather the point.",
    superpower: "When threatened it combines two chemicals stored in separate chambers inside its abdomen, hydroquinone and hydrogen peroxide, which react explosively on contact and produce a boiling toxic spray at 100 degrees Celsius. It can rotate the tip of its abdomen to aim in almost any direction and fires in rapid pulses up to 500 times per second.",
    fun_fact: "The explosion inside the beetle's body produces a audible popping sound that startled scientists when they first studied it up close. Frogs that attempt to swallow a Bombardier Beetle have been observed spitting it back out immediately and sometimes regurgitating it alive up to 107 minutes after swallowing it. The beetle fires from inside the frog's stomach.",
  },
  {
    day: 4,
    title: "Tarantula Hawk",
    category: "Hymenoptera",
    species: "Pepsis grossa — the Tarantula Hawk Wasp, one of the largest wasps in the world and a specialist predator of tarantulas.",
    meet: "The Tarantula Hawk is a wasp that has chosen to make tarantulas its prey. Not small insects. Tarantulas. It is a metallic blue-black wasp with vivid orange wings that can grow up to five centimetres long, and it hunts spiders many times its own size with calm, methodical efficiency.",
    where: "Found across the Americas from the southern United States down through Central and South America, as well as parts of Asia, Africa and Australia. It prefers arid and semi-arid environments where tarantulas are common. It is the state insect of New Mexico.",
    superpower: "It hunts tarantulas, paralyses them with a single precise sting, drags them back to a burrow and lays a single egg on the living but immobilised spider. When the larva hatches it feeds on the still-living tarantula from the inside out, carefully avoiding vital organs to keep it fresh for as long as possible.",
    fun_fact: "The Tarantula Hawk's sting is rated as one of the most painful insect stings on earth on the Schmidt Pain Index, second only to the Bullet Ant. Entomologist Justin Schmidt, who created the index by allowing himself to be stung by hundreds of species, described it as: blinding, fierce, shockingly electric. He recommended the only response was to lie down and scream.",
  },
  {
    day: 5,
    title: "Glowworm",
    category: "Diptera",
    species: "Arachnocampa luminosa — the New Zealand Glowworm, a fungus gnat whose larval stage produces bioluminescent light to attract prey.",
    meet: "The New Zealand Glowworm is not technically a worm. It is the larva of a small fly, and in its larval stage it produces a steady blue-green light and hangs silk threads coated in sticky droplets from cave ceilings. Thousands of them together turn cave roofs into something that looks indistinguishable from a night sky.",
    where: "Caves, overhanging riverbanks and sheltered forest areas throughout New Zealand, with the most famous colonies in Waitomo Caves on the North Island. The conditions must be humid and still as the silk threads cannot function in a breeze.",
    superpower: "The larva produces light through a chemical reaction in a modified excretory organ, essentially glowing with its own waste products. It uses this light to lure flying insects toward the sticky threads, which trap them. The hungrier the larva, the brighter it glows.",
    fun_fact: "The adult glowworm fly has no mouth and no functional digestive system. It hatches, mates, lays eggs and dies, all within a few days, entirely on the energy reserves it stored as a larva. It never eats a single thing as an adult. Its entire life is already spent.",
  },
  {
    day: 6,
    title: "Bullet Ant",
    category: "Hymenoptera",
    species: "Paraponera clavata — the Bullet Ant, the largest ant species in the world and holder of the most painful sting of any insect on earth.",
    meet: "The Bullet Ant is an ant the size of your thumbnail that lives in the rainforests of Central and South America. It is called the Bullet Ant because being stung by one is described as feeling like being shot. It is calm and slow moving for an ant, which somehow makes encountering one more unsettling rather than less.",
    where: "Lowland rainforests from Nicaragua down through Central America and into the Amazon Basin. It nests at the base of trees and forages on the forest floor and in the canopy. Indigenous communities have lived alongside it for thousands of years, sometimes intentionally.",
    superpower: "Its sting delivers a neurotoxin called poneratoxin which disrupts the nervous system and causes waves of intense, throbbing pain lasting up to 24 hours. Unlike most insect stings it does not cause lasting tissue damage. It simply hurts, relentlessly, for an entire day.",
    fun_fact: "The Sateré-Mawé people of the Brazilian Amazon use Bullet Ants in a coming of age ritual for young men. Hundreds of live ants are woven into gloves while sedated, the young men wear the gloves for ten minutes, and must repeat the ritual twenty times to be considered a warrior. The ants wake up during the process.",
  },
  {
    day: 7,
    title: "Fairyfly",
    category: "Hymenoptera",
    species: "Kikiki huna — one of the smallest known fairyfly wasps and one of the tiniest flying insects ever recorded, a parasitoid wasp in the family Mymaridae.",
    meet: "The Fairyfly is so small it is almost conceptually difficult to accept as a real animal. It is smaller than a full stop on this page. It has wings, legs, antennae, eyes and a complete set of internal organs. It is also technically a wasp. The universe apparently decided that size was optional.",
    where: "Fairyflies are found on every continent except Antarctica. Kikiki huna specifically was discovered in Hawaii, Costa Rica and Trinidad. Because of their size they are extraordinarily difficult to find and study, meaning there are likely many more species we have not yet discovered.",
    superpower: "It can fly despite being smaller than many single-celled organisms. Its wings are not flat membranes like most insect wings but fringed bristles, which work more like oars rowing through air than conventional wings. At this scale air behaves more like a thick fluid than a gas.",
    fun_fact: "Kikiki huna measures approximately 0.15 millimetres in length, making it small enough to pass through the eye of a needle with room to spare. It parasitises the eggs of other insects, laying its own egg inside a host egg that is already almost invisibly small. A creature within a creature within nothing you could see.",
  },
  {
    day: 8,
    title: "Zombie Ant",
    category: "Hymenoptera",
    species: "Camponotus leonardi — the Carpenter Ant, known as the Zombie Ant when infected by the parasitic fungus Ophiocordyceps unilateralis.",
    meet: "The Zombie Ant is not a species. It is what happens to a carpenter ant when a parasitic fungus takes control of its body. The ant continues to walk, climb and move but it is no longer making any of its own decisions. Something else is steering. The result is one of the most disturbing things in the natural world.",
    where: "Tropical rainforests in Thailand, Brazil and other humid equatorial regions where the Ophiocordyceps fungus thrives. The phenomenon requires very specific temperature and humidity conditions to complete its life cycle, keeping it confined to particular forest zones.",
    superpower: "The fungus infects the ant, releases chemicals that hijack its nervous system, compels it to climb to a precise height on a plant, bite down on a leaf vein with unusual force, and die there. The fungus then erupts from the ant's head and releases spores onto the ants passing below. It programmes its host to create the perfect spore delivery mechanism.",
    fun_fact: "Ant colonies have developed a collective behaviour in response to zombie ants. Workers recognise infected nestmates by chemical signals and carry them far away from the colony before the fungus can complete its cycle. They have essentially developed a quarantine protocol through millions of years of evolutionary pressure from a single fungus.",
  },
  {
    day: 9,
    title: "Mimic Octopus",
    category: "Octopoda",
    species: "Thaumoctopus mimicus — the Mimic Octopus, a cephalopod discovered only in 1998 off the coast of Sulawesi, Indonesia.",
    meet: "The Mimic Octopus is technically not an insect but it belongs in any conversation about the most extraordinary creatures on earth. It is a small brown and white octopus that can impersonate other animals in real time, selecting whichever disguise it calculates will best deter the specific predator it is currently facing. It thinks about what to become.",
    where: "Tropical Indo-Pacific waters, primarily around Indonesia, the Philippines and the Great Barrier Reef. It prefers shallow, murky river mouths and estuaries with sandy or silty bottoms, where it is an active daytime hunter.",
    superpower: "It can reshape its body and alter its movement to accurately mimic lionfish, flatfish, sea snakes, jellyfish and at least fifteen other species. Crucially it appears to select its disguise contextually. When threatened by a damselfish it tends to mimic a banded sea snake, which is the damselfish's specific natural predator.",
    fun_fact: "The Mimic Octopus was not discovered until 1998 despite living in relatively accessible waters. Scientists believe this is partly because it is so good at looking like other things that researchers simply catalogued the things it was pretending to be. It hid in plain sight inside its own disguises for decades.",
  },
  {
    day: 10,
    title: "Velvet Worm",
    category: "Onychophora",
    species: "Peripatus species — the Velvet Worm, an onychophoran that represents one of the oldest animal lineages on earth, virtually unchanged for over 500 million years.",
    meet: "The Velvet Worm looks soft, slow and harmless. It is covered in what appears to be velvet-like skin and moves with an unhurried, caterpillar-like gait. It is also a highly effective predator that has been hunting in essentially the same way since before the dinosaurs existed, which suggests it found a method that works and decided never to change it.",
    where: "Tropical and subtropical forests across South America, Africa, Southeast Asia, Australia and New Zealand. It requires permanently moist environments and is typically found under logs, leaf litter and bark. It is nocturnal and rarely seen despite being widespread.",
    superpower: "It hunts by firing jets of sticky slime from modified legs on either side of its head, entangling prey instantly. The slime hardens on contact and is made of a protein that is being studied for its potential in biodegradable adhesives and surgical applications. It can hit a target up to 30 centimetres away with remarkable accuracy.",
    fun_fact: "Velvet Worms are sometimes described as a living missing link because they show characteristics of both annelid worms and arthropods, helping scientists understand how legs evolved. Fossils almost identical to living Velvet Worms have been found in Cambrian rock over 500 million years old. It has not needed to change.",
  },
  {
    day: 11,
    title: "Assassin Bug",
    category: "Hemiptera",
    species: "Acanthaspis petax — the Assassin Bug, a member of the Reduviidae family known for wearing its victims as armour.",
    meet: "The Assassin Bug is a predatory insect with an unusual relationship with the concept of recycling. It kills ants, hollows them out and stacks their empty corpses on its own back, wearing them as a disguise and a shield simultaneously. It builds itself a suit of dead ants and then goes looking for more ants to add to the collection.",
    where: "Found across Africa, Southeast Asia and parts of Australia in scrubland, grassland and forest floor environments. It is most common in areas with high ant activity, which makes practical sense given its lifestyle.",
    superpower: "It injects digestive enzymes into prey through a needle-like proboscis, liquefies the insides and drinks them, then adds the empty shell to its back. The pile of dead ants confuses predators, particularly jumping spiders, who struggle to identify the Assassin Bug underneath the camouflage. The stack can contain up to twenty ant corpses.",
    fun_fact: "Researchers tested the effectiveness of the ant-corpse disguise by removing the stack from Assassin Bugs and observing how jumping spiders responded. Spiders attacked the naked bugs immediately and consistently. When the corpse armour was in place, spiders were confused, hesitant or fled entirely. The dead ants are a genuinely functional defence system.",
  },
  {
    day: 12,
    title: "Jewel Wasp",
    category: "Hymenoptera",
    species: "Ampulex compressa — the Emerald Jewel Wasp, a solitary parasitoid wasp found across South Asia, Africa and the Pacific Islands.",
    meet: "The Emerald Jewel Wasp is one of the most beautiful insects in the world and one of the most disturbing. It is a vivid metallic green with coral-coloured legs and moves with precision and apparent calm. It has also developed a method of turning cockroaches into living, compliant nurseries for its larvae through what can only be described as neurosurgery.",
    where: "Tropical regions of South Asia, Africa and the Pacific Islands. It is a ground dweller that hunts in leaf litter and low vegetation. Despite its striking appearance it is rarely noticed because of its small size, around 2 centimetres long.",
    superpower: "It stings a cockroach twice with surgical precision. The first sting temporarily paralyses the front legs. The second sting is delivered directly into the brain, targeting the specific neural circuits that control the escape reflex. The cockroach becomes docile and compliant, capable of walking but no longer motivated to flee. The wasp then leads it by the antenna to a burrow like a dog on a leash.",
    fun_fact: "After leading the lobotomised cockroach into its burrow the wasp lays an egg on its leg, seals the entrance and leaves. The cockroach remains alive and passive while the larva hatches, chews through its abdomen and feeds on its organs in a specific sequence, leaving the vital ones until last to keep it alive as long as possible. The cockroach never recovers its will to escape.",
  },
  {
    day: 13,
    title: "Water Bear",
    category: "Tardigrada",
    species: "Ramazzottius varieornatus — the Tardigrade, commonly called the Water Bear, a microscopic eight-legged animal considered the most resilient creature on earth.",
    meet: "The Water Bear is half a millimetre long, has eight stubby legs, a cylindrical body and a face that looks vaguely like a vacuum cleaner. It lives in moss, soil, leaf litter and water films. It is also essentially indestructible by any standard the universe has so far attempted, which is either reassuring or deeply unsettling depending on your perspective.",
    where: "Everywhere. The Water Bear has been found on every continent including Antarctica, in the Himalayas, in hot springs, in the deep ocean, in urban gutters and on rooftops. If there is a thin film of water somewhere on earth there is almost certainly a Water Bear in it.",
    superpower: "When conditions become hostile it enters a state called cryptobiosis, retracting its legs, expelling almost all its body water and forming a shrivelled barrel shape called a tun. In this state it can survive temperatures from minus 272 degrees Celsius to 150 degrees above, pressures six times that of the deepest ocean, radiation doses hundreds of times fatal to humans, the vacuum of space and complete dehydration for decades.",
    fun_fact: "In 2007 the European Space Agency sent Water Bears into open space on the outside of a satellite. They were exposed to vacuum, extreme temperature fluctuation and intense solar radiation for ten days. When retrieved and rehydrated, a significant number were alive and subsequently reproduced successfully. They had survived open space.",
  },
  {
    day: 14,
    title: "Puss Moth Caterpillar",
    category: "Lepidoptera",
    species: "Megalopyge opercularis — the Puss Moth Caterpillar, also known as the Asp Caterpillar or Southern Flannel Moth larva, found in the southern United States.",
    meet: "The Puss Moth Caterpillar looks like a small, fluffy hairpiece that has somehow found its way onto a leaf. It is covered in soft, silky fur in shades of cream, brown and grey and moves slowly enough that you might be tempted to touch it. This would be a significant mistake. Everything about its appearance is a lie designed to encourage that mistake.",
    where: "Found across the southern United States from New Jersey to Florida and west to Texas, as well as parts of Mexico and Central America. It lives on oak, elm, sycamore and various garden plants and is more common in suburban gardens than most people realise.",
    superpower: "Hidden beneath the soft fur are hollow venomous spines connected to poison glands. Contact with the fur drives these spines into skin where they break off and continue releasing venom. The pain begins immediately and intensifies over the following thirty minutes, spreading up the limb and into the lymph nodes and chest.",
    fun_fact: "The Puss Moth Caterpillar is considered the most venomous caterpillar in the United States. Reports from sting victims describe the pain as comparable to a broken bone or blunt force trauma, not an insect contact. Children are disproportionately affected because the soft fur looks like something a child would naturally want to stroke.",
  },
  {
    day: 15,
    title: "Hummingbird Hawk-Moth",
    category: "Lepidoptera",
    species: "Macroglossum stellatarum — the Hummingbird Hawk-Moth, a moth so precisely similar to a hummingbird in flight that it causes genuine confusion in observers worldwide.",
    meet: "The Hummingbird Hawk-Moth hovers in front of flowers, beats its wings rapidly enough to produce an audible hum, extends a long proboscis to drink nectar and moves with such precision and speed that most people who see it are convinced they have seen a hummingbird. They have not. It is a moth. It is doing this entirely on its own evolutionary terms.",
    where: "Found across southern Europe, Asia and North Africa, with summer migrations into northern Europe including the UK. It visits gardens, meadows and open countryside wherever nectar-producing flowers are available. It flies by day, which is unusual for moths, and is most active in sunshine.",
    superpower: "Its wings beat 70 to 80 times per second, producing the hum. It can hover with exceptional stability, fly backwards, and position itself with the precision needed to insert its proboscis into individual flowers. It does this entirely without the skeletal structure, respiratory system or warm blood of the birds it resembles. Convergent evolution produced an almost identical solution from completely different starting materials.",
    fun_fact: "The Hummingbird Hawk-Moth has been shown in studies to have a remarkably good memory for flowers, remembering the location and timing of rewarding blooms and returning to them at the same time each day. It can also learn to associate colours with rewards faster than honeybees, which are considered among the most cognitively capable of all insects.",
  },
  {
    day: 16,
    title: "Twisted-Wing Parasite",
    category: "Strepsiptera",
    species: "Stylops melittae — a Strepsipteran parasite, representing one of the smallest and most bizarre insect orders, with fewer than 600 known species worldwide.",
    meet: "The Twisted-Wing Parasite spends its entire life inside another insect. The female never leaves her host at all, ever, for any reason. She has no eyes, no legs, no wings and no real body to speak of beyond the reproductive organs that protrude slightly through the host's body wall. She is, in the most literal sense, defined entirely by what she does to something else.",
    where: "Found worldwide wherever their specific hosts live, including bees, wasps, ants and various other insects. Because they are internal parasites they are almost never seen directly. You would only know one was present by examining the host insect closely for the slight protrusion of the parasite's head.",
    superpower: "The male hatches, emerges, flies, finds a female inside a host and mates through a process called traumatic insemination, then dies within hours. The female releases tiny mobile larvae called triungulins that crawl onto flowers, attach themselves to visiting bees and are carried back to the nest, where they burrow into a new host larva to begin the cycle again. The host bee survives but is partially castrated and behaviourally altered.",
    fun_fact: "Insects parasitised by Strepsipterans are described as stylopised, a word that exists only because this situation is common enough to need its own term. Stylopised bees often exhibit altered foraging behaviour, changed flight patterns and disrupted reproduction. The parasite does not kill them. It simply redirects them.",
  },
  {
    day: 17,
    title: "Titan Beetle",
    category: "Coleoptera",
    species: "Titanus giganteus — the Titan Beetle, the largest known beetle species in the world by body length, found in the Amazon rainforest.",
    meet: "The Titan Beetle is a beetle the size of a human hand. It is not a metaphor. Adults can reach 17 centimetres in length, and their mandibles are strong enough to snap a pencil in half or cut into human flesh. It is also, somehow, almost never seen alive in the wild despite its size, which says something about the scale of the Amazon.",
    where: "The Amazon Basin in Venezuela, Colombia, Ecuador, Peru, Bolivia and central Brazil. Adults are typically found near or in large trees in primary rainforest. They are attracted to lights and are occasionally encountered in towns on the rainforest edge. They are most active at night.",
    superpower: "The adult Titan Beetle does not eat. At all. It lives entirely on fat reserves accumulated during its larval stage and spends its adult life flying, finding a mate and dying. Its larval stage has never been directly observed in the wild but is believed to last several years inside dead or decaying hardwood trees. Adults live only weeks.",
    fun_fact: "The larval tunnels of the Titan Beetle, which have been found in fallen trees, measure up to 5 centimetres in diameter. The larva itself has never been seen alive by researchers. Despite the Titan Beetle being known to science since 1778, its complete life cycle remains only partially understood because finding the larva in the vastness of the Amazon has proven essentially impossible.",
  },
  {
    day: 18,
    title: "Dracula Ant",
    category: "Hymenoptera",
    species: "Mystrium camillae — the Dracula Ant, a primitive ant species found in tropical regions notable for the fastest recorded movement of any animal appendage.",
    meet: "The Dracula Ant is a small, pale, largely blind ant that lives underground and feeds on the haemolymph of its own larvae without killing them, which is where the name comes from. The larvae survive the process. The colony continues. It is a deeply uncomfortable arrangement that the colony has apparently decided is preferable to alternatives.",
    where: "Tropical forests of Africa, South and Southeast Asia, and northern Australia. It nests underground or in rotting wood and is rarely seen because it avoids light and surface activity. Despite being widespread it was poorly understood until relatively recently because of how difficult it is to study.",
    superpower: "Its mandibles can snap shut at speeds of up to 90 metres per second, the fastest recorded movement of any animal appendage ever measured. It does this by pressing the tips of its mandibles together under tension and releasing them suddenly, using its jaw as a spring-loaded mechanism. The snap is used to stun prey and fling threats away from the colony.",
    fun_fact: "The Dracula Ant's snap was measured at 5,000 times faster than the blink of a human eye. The acceleration involved is approximately 100,000 g. For comparison, a Formula One racing car experiences around 5 g under braking. The ant generates twenty thousand times that force with a structure smaller than a grain of rice.",
  },
  {
    day: 19,
    title: "Mirror Spider",
    category: "Araneae",
    species: "Thwaitesia argentiopunctata — the Mirror Spider or Sequined Spider, a tiny orb-weaving spider found in Australia notable for the reflective silver patches on its abdomen.",
    meet: "The Mirror Spider is approximately five millimetres long and covered in what appear to be tiny mirror tiles arranged across its abdomen. In sunlight it catches and scatters light like a disco ball. It looks like something a jeweller designed rather than something evolution produced, which is part of what makes it so arresting to encounter.",
    where: "Found in eastern Australia in forest and bushland environments, typically in low shrubs and vegetation. Despite its striking appearance it is small enough and slow enough to be easily overlooked. Most people who find one do so by accident.",
    superpower: "The reflective patches are not fixed. They are made of guanine crystals, the same substance found in fish scales, and they can expand and contract depending on the spider's stress level. When the spider is relaxed the patches are larger. When it is threatened or disturbed they contract and the spider becomes significantly less conspicuous. It can dim its own mirrors.",
    fun_fact: "Scientists are not entirely certain why the Mirror Spider evolved its reflective patches in the first place. One hypothesis is that the flashes of reflected light mimic water droplets and confuse predators. Another is that they attract prey. A third is that they play a role in mating displays. The honest answer is that it is beautiful and the reason remains genuinely unknown.",
  },
  {
    day: 20,
    title: "Portia Spider",
    category: "Araneae",
    species: "Portia fimbriata — the Fringed Jumping Spider, considered the most intelligent invertebrate known to science and a specialist predator of other spiders.",
    meet: "The Portia Spider is a small, shaggy jumping spider that looks like a piece of walking debris. It moves slowly, erratically and with frequent pauses that make it look less like a hunter and more like something being blown by wind. This is deliberate. It is thinking. Portia is widely considered to be the most cognitively complex invertebrate ever studied and it hunts other spiders for a living.",
    where: "Found in tropical forests across Africa, Asia and Australia. It prefers humid forest environments where web-building spiders are abundant. Despite being small and slow it is an apex predator within its ecological niche because of its problem-solving ability rather than any physical advantage.",
    superpower: "It hunts other spiders by plucking their webs to mimic trapped prey or a potential mate, adjusting its signals based on the response it receives. It can plan detour routes to reach prey that it cannot see during the journey, holding the destination in mind while navigating obstacles. It has been observed pausing at decision points for extended periods before choosing a route, behaviour described by researchers as deliberation.",
    fun_fact: "In laboratory experiments Portia was presented with novel situations it could not have encountered in nature and consistently solved them through what appeared to be reasoning rather than instinct. It can learn, adapt and apply solutions across contexts. Researchers who study it tend to describe the experience of watching it think in language that makes other scientists uncomfortable, because the implications about the minimum hardware required for cognition are significant.",
  },
];
