const historyEntries = [
  {
    day: 1,
    title: "The Great Emu War",
    category: "Modern History",
    setting: "Western Australia, 1932. The Australian government declares war on emus. This is not a metaphor.",
    what_happened: "Twenty thousand emus had taken over farmland and the government's solution was two soldiers, two machine guns and ten thousand rounds of ammunition. The emus scattered when fired upon, regrouped in smaller groups and absorbed bullets with what witnesses described as disturbing indifference. After twelve days and nearly three thousand rounds the military withdrew. The emus were unmoved. Australia had declared war on birds and lost.",
    why_matters: "It is one of history's more honest reminders that the assumption of human superiority over nature tends to survive contact with actual nature very poorly. Every era has its own version of this lesson and every era learns it the same way.",
    fun_fact: "Major Meredith, reflecting on the campaign afterwards, said: if we had a military division with the bullet-carrying capacity of these birds it would face any army in the world. The emus are still there.",
  },
  {
    day: 2,
    title: "The Dancing Plague of 1518",
    category: "Medieval History",
    setting: "Strasbourg, Alsace, July 1518. A woman begins dancing in the street and cannot stop.",
    what_happened: "Frau Troffea stepped into the street and started dancing. She danced for days without rest, without food, without explanation. Within a week thirty four people had joined her. Within a month the number had reached four hundred. They danced until their feet bled, until their bodies gave out, until some of them died from exhaustion and heart failure. The city authorities, believing more dancing was the cure, hired musicians to keep them going. It lasted two months. Then it stopped as suddenly as it had started. Nobody has ever fully explained it.",
    why_matters: "The Dancing Plague is one of history's most documented cases of mass psychogenic illness, the phenomenon where stress, fear and social contagion produce real physical symptoms across a group. It has happened many times since, in different forms, and the mechanism is still not fully understood.",
    fun_fact: "The city authorities consulted physicians who ruled out supernatural causes and concluded the dancers were suffering from hot blood. Their official prescription was more dancing. They built a stage, hired professional dancers and a band. The dancing got worse.",
  },
  {
    day: 3,
    title: "Operation Mincemeat",
    category: "World War II",
    setting: "The coast of Spain, April 1943. The British military drops a dead man into the sea carrying fake invasion plans and waits to see if Hitler believes him.",
    what_happened: "British intelligence needed Germany to think the Allied invasion of Europe would come through Greece and Sardinia, not Sicily. Their solution was to obtain a corpse, dress it as a Royal Marine officer, attach a briefcase containing false documents to its wrist and release it off the Spanish coast where German agents would find it. The man they used had died of pneumonia. They gave him a name, a fiancée, a personality and a wallet full of personal effects. Germany found the documents, believed every word and moved troops away from Sicily. The real invasion landed in Sicily and succeeded. A dead man changed the course of the war.",
    why_matters: "Operation Mincemeat is one of the most audacious deceptions in military history and a masterclass in the power of narrative. The British did not just create false information. They created a believable person for the enemy to trust. The story around the documents was as important as the documents themselves.",
    fun_fact: "The man used for the operation was Glyndwr Michael, a homeless Welsh man who had died with no known family. He was given the identity of Captain William Martin. After the war his real name was added to his grave in Spain with the inscription: Glyndwr Michael, served as Major William Martin. He is buried there still.",
  },
  {
    day: 4,
    title: "The Vienna Coincidence",
    category: "Modern History",
    setting: "Vienna, Austria, winter of 1913. The most consequential city in the world contains people who have no idea they are consequential.",
    what_happened: "In a single winter, Adolf Hitler was living in a men's hostel trying to get into art school, Joseph Stalin was in the city writing a paper on nationalism, Leon Trotsky was playing chess at the Café Central and Sigmund Freud was seeing patients a few streets away. None of them knew each other. The city had no idea what it was incubating. Within three decades two of these men would between them be responsible for the deaths of tens of millions of people.",
    why_matters: "History does not announce itself. The people who will define the next chapter are always somewhere right now, unknown and unremarkable. The world never looks like it is standing on the edge of something until it has already fallen.",
    fun_fact: "There is a credible historical theory that Hitler and Stalin may have visited the same café on the same day in 1913. No record exists of them meeting. The idea that they may have passed each other on a Vienna street without a word exchanged is one of those details that makes history feel genuinely strange.",
  },
  {
    day: 5,
    title: "The Man Who Saved the World",
    category: "Cold War",
    setting: "A Soviet nuclear bunker, September 26, 1983. One man receives an alert that the United States has launched nuclear missiles at the Soviet Union.",
    what_happened: "Stanislav Petrov was the duty officer at a Soviet early warning facility when the system reported an incoming American missile strike. His orders were clear: report it up the chain immediately. He did not. Something felt wrong. The system showed only five missiles, which made no strategic sense for a first strike. He waited, heart pounding, for the minutes it would take to confirm. It was a false alarm caused by sunlight reflecting off clouds in a way the satellite had never encountered before. His hesitation may have prevented nuclear war. He never received a medal. He was quietly reprimanded for improper record keeping.",
    why_matters: "The entire architecture of nuclear deterrence depends on human beings making the right call in impossible situations with incomplete information and no time. Petrov made the right call once. We may never know how many times the same situation has arisen or how many times the answer was less fortunate.",
    fun_fact: "Petrov was interviewed about the incident later in life and asked if he considered himself a hero. He said: I was just doing my job. He also said the decision was fifty fifty. He died in 2017. The world learned his name almost entirely by accident.",
  },
  {
    day: 6,
    title: "The Sinking of the Vasa",
    category: "17th Century History",
    setting: "Stockholm harbour, August 10, 1628. Sweden's most powerful warship sets sail for the first time.",
    what_happened: "The Vasa was the pride of the Swedish navy, covered in ornate sculptures, armed with sixty four bronze cannons and built on the personal orders of King Gustav II. It sailed approximately 1,300 metres before the wind caught it, it leaned, water rushed in through the open gun ports and it sank in full view of the Stockholm crowd who had gathered to watch its maiden voyage. It sank in thirty metres of water. The king was not pleased. An inquiry was held. Nobody was punished because nobody wanted to blame the king, who had personally insisted on the design.",
    why_matters: "The Vasa is one of history's most perfect case studies in what happens when nobody is willing to tell the person in charge that their idea will not work. The ship's officers knew it was unstable. They said nothing. Organisations still sink the same way.",
    fun_fact: "The Vasa was raised from the seafloor in 1961, three hundred and thirty three years after it sank. Because the cold, low-salinity water of Stockholm harbour had preserved it almost perfectly, it is now the best preserved 17th century ship in the world and one of Sweden's most visited museums. The failure became the treasure.",
  },
  {
    day: 7,
    title: "The Tanganyika Laughter Epidemic",
    category: "Modern History",
    setting: "A girls' school in Tanganyika, now Tanzania, January 1962. Three students start laughing and cannot stop.",
    what_happened: "Three girls at a boarding school began laughing uncontrollably. The laughter spread. Within days nearly a hundred students were affected, with episodes lasting from a few minutes to several hours. The school was closed. The students went home and the laughter spread to their villages. Other schools in the region were affected. The epidemic lasted eighteen months across multiple communities before finally subsiding. No physical cause was ever identified. The students were not laughing because anything was funny.",
    why_matters: "Like the Dancing Plague four centuries earlier, the Tanganyika epidemic is a documented case of mass psychogenic illness. The body produces real, uncontrollable physical responses to psychological and social stress. It is a reminder that the boundary between mind and body is far less firm than we assume.",
    fun_fact: "Alongside the laughter, affected students also reported crying, fainting, rashes and respiratory problems. The laughter was distressing, not joyful. Witnesses described it as frightening to observe. The affected students were not having a good time.",
  },
  {
    day: 8,
    title: "The Dyatlov Pass Incident",
    category: "Cold War",
    setting: "The Ural Mountains, Soviet Union, February 1959. Nine experienced hikers set up camp on a mountain slope and are never seen alive again.",
    what_happened: "A group of experienced ski hikers led by Igor Dyatlov made camp on a mountain pass during a winter expedition. Something happened in the night that caused all nine of them to tear their way out of their tents from the inside, in temperatures of minus thirty degrees, without boots or coats, and run into the darkness. Some were found with fractured skulls and broken ribs consistent with enormous force but no external wounds. One was missing her tongue. Soviet investigators closed the case with the explanation: a compelling unknown force. It has never been satisfactorily explained.",
    why_matters: "The Dyatlov Pass incident has generated more theories than almost any event in modern history, from avalanche to military testing to infrasound to something stranger. The most recent and widely accepted explanation involves a specific type of delayed snow slab avalanche. Many people find this unsatisfying. The mountain was renamed after Dyatlov.",
    fun_fact: "The Soviet investigators who examined the scene noted the tent had been cut open from the inside with a knife. The footprints in the snow showed the group had walked calmly away from the tent before breaking into a run. Whatever they were running from, they saw it coming.",
  },
  {
    day: 9,
    title: "The Oxford Electric Bell",
    category: "Scientific History",
    setting: "Oxford University, England, 1840. A small electric bell is set ringing. It has not stopped.",
    what_happened: "In 1840 a physicist at Oxford set up a small battery-powered bell as an experiment. The bell began ringing. It is still ringing today. It has rung approximately ten billion times. The battery that powers it has never been replaced or explained. It consists of two dry pile batteries sealed under glass, whose composition is unknown because opening the device to study it would stop the experiment. It sits in the Clarendon Laboratory at Oxford, ticking quietly, and nobody fully understands why it has not run out of power in over one hundred and eighty years.",
    why_matters: "The Oxford Electric Bell sits in a peculiar space between the known and the unknown. The scientific principles behind it are understood in theory. The specific composition of these particular batteries is not. It is a small, persistent reminder that even in well-studied fields there are things that simply continue without explanation.",
    fun_fact: "The bell rings so quietly it is essentially inaudible to the naked ear, which is partly why it has lasted so long. The clapper moves only a tiny distance with each strike to preserve energy. It is the longest-running scientific experiment in history and will likely outlast everyone currently alive.",
  },
  {
    day: 10,
    title: "The Theft of the Mona Lisa",
    category: "Modern History",
    setting: "The Louvre, Paris, August 21, 1911. The most famous painting in the world goes missing and nobody notices for a full day.",
    what_happened: "Vincenzo Peruggia, an Italian handyman who had worked at the Louvre, hid in a closet overnight, removed the Mona Lisa from the wall in the morning, tucked it under his coat and walked out. The painting was missing for twenty-four hours before anyone noticed. When they did notice, the Louvre closed for a week. Kafka wrote about it. Picasso was briefly a suspect. The painting was missing for two years before Peruggia tried to sell it to an art dealer in Florence who called the police. Peruggia believed the painting belonged in Italy. He served seven months in prison. The Mona Lisa returned to Paris more famous than it had ever been.",
    why_matters: "Before the theft the Mona Lisa was one of many admired works in the Louvre. The two-year absence, the global search and the eventual recovery turned it into an icon. The painting is famous partly because it was stolen. The theft created the myth.",
    fun_fact: "While the Mona Lisa was missing, more people visited the Louvre to see the empty space on the wall than had ever come to see the painting itself. The empty hook drew larger crowds than the masterpiece. People wanted to witness the absence.",
  },
  {
    day: 11,
    title: "The War of Jenkins' Ear",
    category: "18th Century History",
    setting: "The British Parliament, 1738. A sea captain produces a severed ear in a jar and starts a war.",
    what_happened: "Captain Robert Jenkins claimed Spanish coast guards had boarded his ship, tied him to a mast and cut off his ear in 1731. Seven years later he brought the ear, preserved in a jar, to the British Parliament and displayed it during a debate about Spanish aggression. Parliament was outraged. Britain declared war on Spain. The war lasted nine years, merged into the larger War of the Austrian Succession and settled nothing. It is remembered almost entirely because of the ear.",
    why_matters: "The War of Jenkins' Ear is history's most vivid example of how a single emotionally resonant image can override strategic thinking entirely. The ear was the perfect provocation. It was personal, physical and impossible to argue with. Governments still go to war for similar reasons, just without the jar.",
    fun_fact: "Jenkins, when asked by a member of Parliament what he had done when his ear was cut off, reportedly replied: I commended my soul to God and my cause to my country. It is one of the most composed responses to ear removal in recorded history.",
  },
  {
    day: 12,
    title: "The Miracle of Dunkirk",
    category: "World War II",
    setting: "The beaches of Dunkirk, France, May 1940. The British army is trapped, surrounded and about to be destroyed.",
    what_happened: "Three hundred and thirty thousand Allied soldiers were stranded on the beaches of Dunkirk with the German army closing in on three sides and the English Channel behind them. The Royal Navy did not have enough ships. So Britain sent everything else. Fishing boats, pleasure cruisers, ferries, lifeboats and private yachts crossed the Channel in what became known as the Little Ships. Over nine days they evacuated the army that would go on to fight the rest of the war. Churchill called it a miracle. He also called it a colossal military disaster, which it also was.",
    why_matters: "Dunkirk is remembered as a triumph of collective will but Churchill was right on both counts. An army that should have been destroyed escaped to fight again. The evacuation saved Britain's ability to continue the war. But it only became necessary because of catastrophic strategic failures in the weeks before.",
    fun_fact: "Among the Little Ships that crossed to Dunkirk was a pleasure boat called the Sundowner, skippered by retired naval officer Charles Lightholler. He had previously survived the sinking of the Titanic. He brought back a hundred and thirty men on a boat rated for twenty one.",
  },
  {
    day: 13,
    title: "The Children's Crusade",
    category: "Medieval History",
    setting: "France and Germany, 1212. Tens of thousands of children set off to reclaim Jerusalem. None of them make it.",
    what_happened: "In 1212 a French shepherd boy named Stephen claimed God had given him a letter to deliver to the King of France and that he could lead a crusade that would succeed where adult armies had failed. Tens of thousands of children and young people followed him to the Mediterranean coast, where Stephen had promised the sea would part. It did not. Some turned back. Some reportedly boarded ships provided by merchants who then sold them into slavery in North Africa. The crusade that set out to liberate Jerusalem never left Europe. Many of those who set out were never seen again.",
    why_matters: "The Children's Crusade is one of history's most haunting examples of the intersection of faith, manipulation and collective delusion. Whether Stephen genuinely believed what he preached or not, thousands of children followed him toward something that was never going to happen. The certainty of the believers made the outcome no less catastrophic.",
    fun_fact: "Historians debate whether the Children's Crusade involved actual children or whether the Latin word pueri, meaning children, was used to describe poor people and peasants rather than literal minors. The reality may have been a movement of dispossessed young adults. The truth is probably more complicated and no less sad.",
  },
  {
    day: 14,
    title: "The London Beer Flood",
    category: "Industrial History",
    setting: "St Giles, London, October 17, 1814. A brewery tank fails and London gets a wave.",
    what_happened: "A large fermentation vat at the Meux and Company Brewery ruptured, triggering a chain reaction that released over a hundred thousand gallons of beer into the streets of St Giles. The wave was reportedly over four metres high. It demolished two houses, flooded basements where families were living and killed eight people, most of whom drowned. Several died when a wall collapsed under the weight of the liquid. Local residents reportedly scooped beer from the streets for hours. The brewery was taken to court and found not guilty on the grounds that it was an act of God.",
    why_matters: "The London Beer Flood sits at the intersection of industrial expansion, urban poverty and the complete absence of safety regulation that defined early industrial cities. The families killed were living in basement dwellings directly beneath the brewery. The poorest people occupied the most dangerous spaces and had no legal recourse when those spaces became fatal.",
    fun_fact: "Some accounts claim that locals gathered to drink the beer flowing through the streets rather than fleeing it. A secondary fatality reportedly occurred when a group who had consumed large quantities of the flood beer died of alcohol poisoning the following day. The brewery compensated no one.",
  },
  {
    day: 15,
    title: "The Trojan Horse",
    category: "Ancient History",
    setting: "Troy, circa 1200 BCE. A ten-year war ends because someone brings a gift they probably should not have accepted.",
    what_happened: "After ten years of siege the Greeks appeared to give up, sail away and leave behind an enormous wooden horse as an offering to the gods. The Trojans, despite several warnings including from their own priest Laocoon who said I fear Greeks even when they bring gifts, brought the horse inside the city walls. That night Greek soldiers hidden inside the horse crept out, opened the gates and Troy was destroyed. The phrase do not look a gift horse in the mouth does not apply here. They should have looked inside the horse.",
    why_matters: "Whether the Trojan Horse is literal history or myth, the strategic principle it represents has been used in warfare, business and politics ever since. The most dangerous threats are the ones that arrive looking like gifts. Deception that exploits trust is more powerful than any frontal attack.",
    fun_fact: "The phrase Trojan Horse entered computing language to describe malware that disguises itself as legitimate software. The ancient story became the name for one of the most common forms of modern cyberattack. Three thousand years later the metaphor is still the most accurate one available.",
  },
  {
    day: 16,
    title: "The Race to the South Pole",
    category: "Exploration History",
    setting: "Antarctica, 1911. Two expeditions race to be the first to reach the South Pole. One arrives to find the other has already been there.",
    what_happened: "Norwegian Roald Amundsen and British Robert Falcon Scott both set out for the South Pole in 1911. Amundsen arrived on December 14 and left a tent and a letter for Scott. Scott arrived thirty-four days later to find the Norwegian flag already planted. He wrote in his diary: the worst has happened. Scott and his four companions all died on the return journey, caught in a blizzard approximately eighteen kilometres from a supply depot. Amundsen returned home safely and lived another seventeen years.",
    why_matters: "The contrast between the two expeditions became a masterclass in preparation, decision making and the difference between romantic ambition and systematic planning. Amundsen had studied Inuit techniques, used dogs and planned meticulously. Scott brought motorised sledges that broke down, ponies unsuited to Antarctic conditions and an almost literary belief in the nobility of suffering.",
    fun_fact: "Scott's last diary entry was written on March 29, 1912. It ended: for God's sake look after our people. His body, the diary and his final letters were found eight months later by a search party. The diary was published and Scott became a national hero. Amundsen, who had done everything right, was largely forgotten outside Norway for decades.",
  },
  {
    day: 17,
    title: "The Defenestration of Prague",
    category: "Early Modern History",
    setting: "Prague Castle, May 23, 1618. A political disagreement is resolved by throwing people out of a window.",
    what_happened: "Protestant Bohemian nobles, furious at the Catholic Habsburg authorities, marched into Prague Castle, held a brief trial and threw three Catholic officials out of a third-floor window. The drop was approximately twenty-one metres. All three survived. The Catholics claimed they had been saved by angels. The Protestants pointed out they had landed in a pile of rubbish. The incident is considered the opening act of the Thirty Years War, one of the most destructive conflicts in European history, which killed roughly a third of the population of Central Europe.",
    why_matters: "The Defenestration of Prague is history's most literal example of a political flashpoint. The actual act of throwing people from windows accomplished nothing militarily. But it was a declaration that negotiation was over. The symbolism of the act mattered far more than the physics of it.",
    fun_fact: "This was actually the second Defenestration of Prague. The first occurred in 1419 when Hussite protesters threw Catholic councillors from a town hall window, triggering the Hussite Wars. Prague has a history with windows that no other city can claim.",
  },
  {
    day: 18,
    title: "The Invention of the Sandwich",
    category: "18th Century History",
    setting: "London, 1762. A man is too busy gambling to eat a meal and accidentally changes culinary history.",
    what_happened: "John Montagu, the Fourth Earl of Sandwich, was reportedly so committed to a card game that he refused to leave the table to eat. He ordered his servants to bring him meat tucked between two slices of bread so he could eat with one hand and keep playing with the other. Other gamblers began ordering the same thing. The name stuck. The Earl did not invent the concept of putting food between bread, which humans had been doing for centuries. He invented the name and the cultural moment that made it famous.",
    why_matters: "The sandwich story is a reminder that most things we consider inventions are actually moments of naming and popularisation rather than genuine origination. The Earl did not create something new. He made something ordinary visible enough to be noticed and copied at scale. That is often how cultural shifts actually work.",
    fun_fact: "The Earl of Sandwich was also the First Lord of the Admiralty and gave his name to the Sandwich Islands, now known as Hawaii, through Captain Cook's explorations. He is therefore responsible for both Hawaii and the sandwich, which is an extraordinary legacy for a man primarily remembered for eating at a card table.",
  },
  {
    day: 19,
    title: "The Radium Girls",
    category: "Industrial History",
    setting: "Orange, New Jersey, 1917. Young women paint watch dials with radium paint and are told it is safe.",
    what_happened: "During World War One, hundreds of young women were employed to paint luminous numbers on watch dials using radium paint. Their supervisors told them the paint was harmless and encouraged them to point their brushes with their lips to get a fine tip. The women began to fall ill. Their jaws deteriorated. Their bones broke spontaneously. Some glowed in the dark. When they sued the company, the US Radium Corporation argued the women were dying of syphilis. The women fought back, many of them too ill to raise their arms, and won. Their legal case established the right of workers to sue employers for damages and transformed industrial safety law.",
    why_matters: "The Radium Girls changed labour law permanently. Their case established that corporations could be held legally responsible for knowingly exposing workers to danger. Every workplace safety regulation that followed owes something to five women in New Jersey who refused to be told their deaths were their own fault.",
    fun_fact: "The radium had been ingested in such quantities that the women's bodies remained radioactive after death. Decades later their remains were exhumed for research and were still emitting measurable radiation. Their bones told the story their employers had tried to bury.",
  },
  {
    day: 20,
    title: "The Night Witches",
    category: "World War II",
    setting: "The Eastern Front, 1942. The Soviet Air Force runs out of planes and gives a regiment of women plywood crop dusters instead.",
    what_happened: "The 588th Night Bomber Regiment of the Soviet Air Force was an all-female unit given obsolete Polikarpov Po-2 biplanes, originally designed for crop dusting, because better aircraft were needed elsewhere. The planes had no radar, no radio, no guns and no parachutes. The women flew up to eighteen missions a night, in the dark, over enemy lines. They would cut their engines on approach and glide silently to their targets, dropping bombs before restarting. German soldiers called them the Night Witches because the sound of their gliding planes resembled a witch's broomstick. They flew thirty thousand missions over four years.",
    why_matters: "The Night Witches flew more missions than almost any other unit in the war with the worst equipment available. They received the fewest resources and produced some of the highest results. Twenty three of them were awarded the title Hero of the Soviet Union, the highest military honour. Their story was suppressed after the war and most of the world did not learn their names until decades later.",
    fun_fact: "Because their planes were so slow that German fighter jets could not safely reduce speed enough to shoot them down without stalling, the Luftwaffe developed specific tactics for hunting them involving multiple aircraft working in coordination. The Germans took the crop dusters seriously enough to build strategies around them. The women took this as a compliment.",
  },
];
