const wordsEntries = [
  {
    day: 1,
    title: "Saudade",
    category: "Portuguese",
    language: "Portuguese, deeply rooted in Brazilian and Portuguese culture. The word is considered so central to the Portuguese identity that there is an entire musical genre, Fado, built around the feeling it describes.",
    meaning: "A melancholic longing for something or someone you love that is absent, lost or may never have existed at all. Not quite grief, not quite nostalgia. Something in between that has no English equivalent.",
    feeling: "It is a Sunday afternoon and something is missing but you cannot name it. It is the ache of a song that reminds you of a person. It is missing a version of your life you never actually lived. Saudade is not sadness exactly. It is the presence of an absence. The Portuguese say you can feel saudade for something you have never had, which means it is not really about loss at all. It is about longing itself.",
    fun_fact: "The word appears in Portuguese literature as far back as the 13th century and was once described by the writer Manuel de Melo as a pleasure you suffer and a pain you enjoy. The Portuguese consider it untranslatable on principle, not because other languages lack the words but because they believe no other culture feels it quite the same way.",
  },
  {
    day: 2,
    title: "Uitwaaien",
    category: "Dutch",
    language: "Dutch, from the Netherlands. The word combines uit meaning out and waaien meaning to blow or to be windy. It is an ordinary, practical word in Dutch, used the way English speakers might say going for a walk.",
    meaning: "To go outside in the wind specifically to clear your head. Not just a walk. A deliberate exposure to moving air as a form of mental reset. The Dutch treat it as a normal and necessary thing to do.",
    feeling: "You have been inside too long. The thoughts have been circling. There is a particular kind of mental fog that comes not from tiredness but from too much stillness, too much screen, too much room. Uitwaaien is the belief that wind can fix this. That moving air has something to offer that warm rooms do not. You go outside, the wind pushes against you, and something loosens. The Dutch built a word around this because they know it works.",
    fun_fact: "The Netherlands is one of the windiest countries in Europe, which may explain why the Dutch developed a specific cultural relationship with wind rather than simply enduring it. The country's landscape of flat open land and sea means wind is inescapable. At some point the Dutch decided to use it rather than avoid it.",
  },
  {
    day: 3,
    title: "Torschlusspanik",
    category: "German",
    language: "German, literally translated as gate closing panic. German has a long tradition of compound words that describe precise emotional states that other languages require entire sentences to convey.",
    meaning: "The panic that comes from feeling that time is running out on your opportunities. The anxiety that doors are closing, that certain paths are becoming unavailable, that the window for something important is narrowing. Often felt around age and life milestones.",
    feeling: "It arrives quietly and then all at once. You are fine and then you are suddenly aware of how much time has passed and how little of what you imagined has happened yet. It is not regret exactly because the thing has not been lost yet. It is the fear that it is about to be. The gate is not closed. But you can hear it moving.",
    fun_fact: "The original medieval meaning was entirely literal. Town gates closed at sunset and anyone left outside would be locked out until morning, exposed to whatever dangers the night held. The modern psychological meaning evolved from that very real physical anxiety of watching a gate close with you on the wrong side of it.",
  },
  {
    day: 4,
    title: "Mamihlapinatapai",
    category: "Yaghan",
    language: "Yaghan, the language of the indigenous Yaghan people of Tierra del Fuego at the southern tip of South America. The language is nearly extinct, with only one known fluent native speaker remaining as of recent years.",
    meaning: "The wordless look shared between two people who both want the same thing but neither is willing to be the first to say so or act on it. A moment of mutual unspoken understanding and mutual hesitation.",
    feeling: "You both know. The silence is not empty, it is full of the thing neither of you is saying. There is something almost comfortable about it and something unbearable. The moment stretches. One of you will have to move first, or neither of you will, and the moment will pass into the category of things that almost happened. This word exists because someone needed to name the exact texture of that pause.",
    fun_fact: "Mamihlapinatapai has been listed in the Guinness World Records as the most succinct word, meaning the word that packs the most meaning into the fewest sounds relative to what it describes. The entire concept requires a paragraph in English. The Yaghan captured it in one word.",
  },
  {
    day: 5,
    title: "Hygge",
    category: "Danish / Norwegian",
    language: "Danish and Norwegian, pronounced roughly hoo-ga. The concept became internationally known after Danish happiness consistently ranked among the highest in the world and researchers began asking why. Hygge was part of the answer.",
    meaning: "A quality of cosiness, warmth and convivial togetherness that produces a feeling of contentment and wellbeing. Not a thing you have but a feeling you create, usually with other people, warmth, food and the deliberate setting aside of stress.",
    feeling: "The candles are lit. It is dark outside. Nobody is checking their phone. The conversation is unhurried. There is something warm to drink and something good to eat and nobody has anywhere to be. Hygge is not an accident. The Danes create it deliberately, as a practice, especially in winter. They decided that if the dark and cold were unavoidable, they would build something worth staying inside for.",
    fun_fact: "Denmark consistently ranks as one of the happiest countries in the world despite having long dark winters, high taxes and famously grey weather. Researchers attribute part of this to the cultural practice of hygge, the deliberate cultivation of warmth and togetherness as a counterweight to difficult conditions. Happiness, the Danes suggest, is something you arrange.",
  },
  {
    day: 6,
    title: "Mono no Aware",
    category: "Japanese",
    language: "Japanese, from the classical literary tradition. The phrase translates roughly as the pathos of things or an empathy toward things. It is central to Japanese aesthetics and appears throughout Japanese literature, poetry and visual art.",
    meaning: "The bittersweet awareness of impermanence. The gentle sadness that comes from knowing beautiful things do not last, combined with a deeper appreciation of them because of that knowledge. Not depression. Something closer to grateful melancholy.",
    feeling: "Cherry blossoms are the classic image because they bloom for only a week or two. Their beauty is inseparable from their brevity. Mono no aware is the feeling you have watching them fall, knowing that the falling is part of what makes them beautiful. It is the emotion you feel at the end of something wonderful when you understood while it was happening that it would end. The Japanese built an entire aesthetic around this feeling because they decided it was worth honouring rather than avoiding.",
    fun_fact: "The concept was formally articulated by the 18th century Japanese scholar Motoori Norinaga, who argued that mono no aware was the defining emotional quality of Japanese literature. He believed it was what separated Japanese sensibility from Chinese and other traditions. The cherry blossom festivals held across Japan every spring are in part a collective, annual practice of this exact feeling.",
  },
  {
    day: 7,
    title: "Fernweh",
    category: "German",
    language: "German, literally translated as farsickness or distance pain. It is the counterpart to Heimweh, which means homesickness. Where homesickness is a longing for where you are from, Fernweh is a longing for somewhere you have never been.",
    meaning: "An ache for distant places. A longing for travel and elsewhere that feels almost physical. Not wanderlust, which is a desire. Fernweh is closer to a pain, an absence felt in the body for places you have not yet seen.",
    feeling: "You see a photograph of somewhere you have never been and feel, inexplicably, that you are missing it. A landscape pulls at something. A city you have only read about feels like an absence in your life rather than simply an unknown. Fernweh is the travel version of saudade, except the longing is for something that has not happened yet rather than something that is gone. It is being homesick for a home you have never had.",
    fun_fact: "The word entered German usage in the 19th century during the Romantic movement, when poets and philosophers became preoccupied with the idea of elsewhere as a source of meaning. The Romantics believed that the horizon contained something the present location could not offer. Fernweh was their word for that belief lived as a feeling.",
  },
  {
    day: 8,
    title: "Palegg",
    category: "Norwegian",
    language: "Norwegian, a completely ordinary and practical word in everyday Norwegian life. It refers specifically to anything you put on top of a slice of bread. Any topping. Any of them.",
    meaning: "Anything and everything you might put on a slice of bread. Butter, cheese, jam, cold cuts, salmon, cucumber, anything at all. The Norwegians found it necessary to have a single word for this entire category of things.",
    feeling: "There is something quietly wonderful about a language deciding that the universe of bread toppings deserves its own word. Norwegian open-faced sandwiches, called smørbrød, are a serious cultural institution. The variety and care that goes into what sits on top of the bread warranted its own vocabulary. English speakers must say what are you putting on your sandwich. Norwegians just say what palegg are you having, and everyone understands.",
    fun_fact: "Norway consistently ranks among the highest consumers of bread per capita in the world. The open-faced sandwich is eaten at almost every meal. Given this context it makes complete sense that the Norwegian language would develop precise and efficient vocabulary around the act of constructing one. The culture shapes the language.",
  },
  {
    day: 9,
    title: "Schadenfreude",
    category: "German",
    language: "German, from Schaden meaning harm or damage and Freude meaning joy or pleasure. It is one of the most widely borrowed German words in the English language, used regularly in English writing and conversation because English has no equivalent.",
    meaning: "The pleasure derived from the misfortune of others. Not cruelty exactly, because it does not require wishing harm on anyone. It is the satisfaction felt when something bad happens to someone, particularly someone who seemed to deserve it.",
    feeling: "Someone who was insufferably confident fails publicly. A boastful prediction turns out to be wrong. The person who cut in front of you in traffic gets pulled over a kilometre later. Schadenfreude is the small, slightly guilty warmth of watching that happen. Most people feel it. Few people admit it. The Germans gave it a name, which was either very honest of them or very strategic in making everyone else feel better about having the feeling.",
    fun_fact: "Neuroscience has confirmed that schadenfreude is a real and distinct emotional response. Brain imaging studies show that the reward centres of the brain activate when people observe misfortune befalling someone they consider a rival or someone they believe acted unfairly. The pleasure is not imagined. It is measurable. We are all, apparently, a little German in this regard.",
  },
  {
    day: 10,
    title: "Aware",
    category: "Japanese",
    language: "Japanese, pronounced ah-wah-reh. Distinct from mono no aware, which is a compound concept. Aware on its own is one of the oldest words in the Japanese language and appears throughout classical literature as far back as the eighth century.",
    meaning: "A spontaneous emotional response to beauty or pathos, a sudden Oh of feeling triggered by something moving. Not a sustained emotion but a flash of being struck, of being emotionally pierced by a moment of beauty or sadness.",
    feeling: "It is the intake of breath when you see something unexpectedly beautiful. The moment a piece of music catches you off guard. Looking up from your phone and noticing the quality of the light. Aware is the gasp before you have decided whether you are happy or sad. It is the pure initial impact of being moved before your mind has categorised what you are feeling. The Japanese considered this response important enough to name.",
    fun_fact: "The literary critic and scholar Motoori Norinaga, who also wrote about mono no aware, argued that aware was the foundation of all genuine emotional experience in Japanese poetry. He believed that literature which failed to produce aware in the reader had failed at its most basic task. The emotional gasp was not decoration. It was the point.",
  },
  {
    day: 11,
    title: "Dépaysement",
    category: "French",
    language: "French, from dépayser meaning to remove from one's country or to disorient. The French have a long tradition of precise emotional vocabulary and this word captures something most travellers have felt but never named.",
    meaning: "The disorienting but often exhilarating feeling of being in a foreign place, removed from everything familiar. The particular sensation of being a stranger somewhere, where everything is slightly different and your usual habits and identity do not quite apply.",
    feeling: "You are somewhere that does not know you. The street signs are in a different language. You do not know which shop sells what. The social rules are slightly different and you have to pay attention to everything rather than moving through the world on autopilot. Dépaysement captures the fact that this is both unsettling and freeing. You are nobody here. You could be anyone. The unfamiliarity is the point.",
    fun_fact: "The Surrealist art movement in France deliberately sought dépaysement as a creative strategy, placing familiar objects in unfamiliar contexts to produce the same disorientation in the viewer. Salvador Dalí and René Magritte built careers on manufacturing the feeling artificially. They believed that removing something from its expected context was how you made people actually see it.",
  },
  {
    day: 12,
    title: "Lagom",
    category: "Swedish",
    language: "Swedish, considered one of the most characteristically Swedish concepts in the language. The word is used constantly in everyday Swedish life and is often cited by Swedes themselves as capturing something essential about their culture and values.",
    meaning: "Not too much, not too little. Just the right amount. Exactly enough. The word resists translation because English tends toward extremes, more or less, better or worse. Lagom exists in the space in between and insists that space is not compromise but a destination in itself.",
    feeling: "There is a Swedish cultural comfort with sufficiency that other cultures find puzzling. Not the best. Not the most. Not maximum. Lagom. The house is lagom sized. The portion is lagom. The temperature is lagom. It sounds like modesty but it is not self-denial. It is the genuine belief that exactly enough is not a consolation prize. It is actually the goal. English has no word for this because English culture is not entirely sure it believes it.",
    fun_fact: "One popular folk etymology suggests lagom derives from laget om, meaning around the team, referring to the Viking practice of passing a shared drinking horn around a group where each person should drink their fair share and no more. Whether true or not, the story captures the collective, equitable spirit the word carries.",
  },
  {
    day: 13,
    title: "Toska",
    category: "Russian",
    language: "Russian, considered by many writers and translators to be one of the most difficult Russian words to render in English. Vladimir Nabokov, who wrote in both Russian and English, spent considerable effort trying to explain it to English readers.",
    meaning: "A longing with nothing to long for. A spiritual anguish without specific cause. A dull ache of the soul, a vague restlessness, a yearning that has no object. Not depression. Not sadness about something. A free-floating melancholy that simply exists.",
    feeling: "It is three in the afternoon and you are not sad about anything in particular but something is heavy. Nothing is wrong. Nothing is right. There is a vague sense that something is missing but you could not say what. Toska is this feeling given a name and taken seriously. The Russians did not decide this was a problem to solve. They named it, wrote poetry about it and considered it part of the texture of being alive. That alone is worth something.",
    fun_fact: "Nabokov described toska as follows: at its deepest and most painful it is a sensation of great spiritual anguish, often without any specific cause. At less morbid levels it is a dull ache of the soul, a longing with nothing to long for. A sick pining. A vague restlessness. He spent a paragraph on it. The Russians spent one word.",
  },
  {
    day: 14,
    title: "Meraki",
    category: "Greek",
    language: "Greek, from the Turkish merak meaning labour of love or to do something with pleasure. Used in modern Greek to describe a quality of engagement and devotion that transforms ordinary work into something personal.",
    meaning: "To do something with soul, creativity and love. To put a piece of yourself into what you are doing. The quality of total absorption and care that makes the difference between completing a task and genuinely making something.",
    feeling: "You are cooking and it is not just about the food. You are writing and it is not just about finishing. You are arranging something, making something, building something and there is a quality of attention that goes beyond what is required. Something of you is going into it. Meraki is that quality. The Greeks noticed that some people bring themselves to their work and some do not, and decided the difference was important enough to name.",
    fun_fact: "The concept of meraki is related to the Greek idea of philotimo, which roughly translates as love of honour, the deep sense of personal dignity and responsibility that comes from caring about how you do things. Both words point to the same cultural conviction that how you do something matters as much as whether you do it.",
  },
  {
    day: 15,
    title: "Ikigai",
    category: "Japanese",
    language: "Japanese, from iki meaning life and gai meaning worth, value or result. The concept has ancient roots in Japanese culture but became internationally prominent in the early 2000s when researchers began linking it to the remarkable longevity of people in Okinawa.",
    meaning: "The reason you get up in the morning. The intersection of what you love, what you are good at, what the world needs and what you can be paid for. Your reason for being. Not a job title. Not a goal. The underlying thing that makes your existence feel purposeful.",
    feeling: "Most people can identify parts of it. What they love. What they are good at. Fewer can name where all four circles overlap. Ikigai is not always dramatic. For some people it is raising children. For others it is a craft. For others still it takes decades to find. The Japanese do not treat the search as a failure. They treat it as one of the central activities of a human life, worth pursuing carefully and without rushing.",
    fun_fact: "A 2008 study of Okinawans, who have among the highest life expectancy and concentration of centenarians in the world, found that having a clear ikigai was one of the strongest predictors of longevity in the study group. People who could articulate their reason for being lived longer. The researchers could not fully explain the mechanism. The Okinawans were not surprised.",
  },
  {
    day: 16,
    title: "Vrijheid",
    category: "Dutch",
    language: "Dutch, translating directly as freedom. But the Dutch relationship with this word carries specific weight given the country's history of occupation during World War Two and its deeply ingrained cultural value of individual autonomy and tolerance.",
    meaning: "Freedom, but carried with a particular Dutch cultural gravity. Not freedom as an abstract political concept but freedom as something earned, remembered, actively chosen and fiercely protected in daily life. The Dutch do not take it as a given.",
    feeling: "Every year on May 5th the Netherlands celebrates Bevrijdingsdag, Liberation Day, marking the end of Nazi occupation in 1945. The word vrijheid on that day carries five years of occupation inside it. The freedom to cycle where you want, to say what you think, to live as you choose. The Dutch built a culture around these things not because they came easily but because they once did not exist. Vrijheid is the word that remembers that.",
    fun_fact: "The Netherlands was occupied by Nazi Germany from May 1940 to May 1945. During that period the Dutch resistance produced some of the most active and organised underground networks in occupied Europe. The Anne Frank House in Amsterdam is the most visited reminder of what vrijheid costs when it is taken away.",
  },
  {
    day: 17,
    title: "Cafuné",
    category: "Brazilian Portuguese",
    language: "Brazilian Portuguese, specific to Brazil rather than Portugal. The word has no equivalent in European Portuguese or in any other major language, making it one of those words that feels like it should exist everywhere but was only named in one place.",
    meaning: "The act of tenderly running your fingers through someone's hair. Not styling it. Not washing it. Simply the gentle, affectionate gesture of running fingers through another person's hair as an act of care and closeness.",
    feeling: "It is one of those gestures that exists in every culture but that most languages have never found a word for. Someone is lying with their head near you and without thinking you reach out and run your fingers through their hair. There is no agenda to it. It is purely about proximity and tenderness. The Brazilians decided this deserved a name, and having a name for it somehow makes the gesture feel more deliberate, more recognised, more real.",
    fun_fact: "Brazil has a remarkably rich vocabulary for physical affection and closeness, possibly reflecting the country's deeply social and tactile culture. The warmth that characterises Brazilian social interaction produced a language that needed words for the specific textures of closeness that other languages left unnamed.",
  },
  {
    day: 18,
    title: "Sehnsucht",
    category: "German",
    language: "German, roughly translated as yearning or longing but considered by German speakers to be far more specific and profound than either of those words conveys. C.S. Lewis spent considerable time writing about this word because he believed it described a fundamental human experience.",
    meaning: "An intense, deep longing or craving for something, often something you cannot name or that may not exist. A yearning for an ideal, an elsewhere, a state of being that feels just out of reach. Not the same as wanting something specific. More like a hunger for something you cannot fully articulate.",
    feeling: "It is the feeling at the end of a perfect day that it was somehow not enough. The sense while reading a beautiful book that the world inside it is more real than the one outside. The inexplicable ache triggered by a piece of music. Sehnsucht is the yearning for something beyond what is available in ordinary life. C.S. Lewis believed it was a clue, that the longing pointed toward something real. Others believe it simply points to the gap between what we can imagine and what we can have.",
    fun_fact: "C.S. Lewis wrote extensively about Sehnsucht, calling it Joy, a technical term in his writing for this specific longing. He described it as an unsatisfied desire which is itself more desirable than any other satisfaction. He believed that the existence of the longing was evidence of something worth longing for. Whether or not you agree, the feeling he was describing is exactly Sehnsucht.",
  },
  {
    day: 19,
    title: "Ubuntu",
    category: "Nguni Bantu",
    language: "Nguni Bantu languages of southern Africa, including Zulu and Xhosa. The concept is central to many southern and eastern African cultures and has been adopted into global discourse through the writings of Desmond Tutu and Nelson Mandela among others.",
    meaning: "I am because we are. The belief that a person is a person through other people. That individual humanity is inextricably bound to community, that you cannot be fully human in isolation, that your humanity is reflected and completed in your relationships with others.",
    feeling: "Ubuntu is not a feeling exactly. It is a way of seeing. When you help someone not because it benefits you but because their flourishing is part of yours. When a community celebrates an individual's success as collective success. When the boundary between I and we becomes less important than the connection between them. It is a word that challenges the Western assumption that the individual is the primary unit of meaning. Ubuntu says the relationship is.",
    fun_fact: "Nelson Mandela described ubuntu as the profound sense that we are human only through the humanity of others, that if we are to accomplish anything in this world it will in equal measure be due to the work and achievements of others. Desmond Tutu used it as the theological foundation for the Truth and Reconciliation Commission after apartheid, arguing that healing required restoring relationship, not just punishing wrongdoing.",
  },
  {
    day: 20,
    title: "Zwischenraum",
    category: "German",
    language: "German, literally meaning the space in between. German has an extraordinary capacity for compound words that name specific spaces, states and transitions that other languages leave unnamed. Zwischenraum is among the most evocative.",
    meaning: "The space between things. Not the things themselves but the gap, the interval, the pause. In architecture it refers to negative space. In music it is the silence between notes. In life it is the in-between moments, the transitions, the waiting spaces that most languages have no word for.",
    feeling: "You are between one thing and the next and the in-between has its own quality that is easy to miss if you are always rushing toward arrival. The pause before the answer. The corridor between two rooms. The moment after one chapter ends and before the next begins. Zwischenraum asks you to notice the space itself, not just what it separates. Some of the most important things happen there.",
    fun_fact: "In typography, Zwischenraum refers specifically to the space between letters and words, called kerning and tracking in English. Type designers spend enormous amounts of time on these spaces because the gaps between characters affect readability as profoundly as the characters themselves. The space between things shapes how we experience the things.",
  },
];
